# import timm
# import torch
# from PIL import Image
# from timm.data import resolve_data_config
# import torchvision.transforms as transforms
# from timm.data.transforms_factory import create_transform
# import matplotlib.pyplot as plt

from torchvision.transforms import Resize, CenterCrop, ToPILImage
from torchvision.transforms import Normalize


def inverse_transform(image):
    # inverse transform generated by request from ChatGPT by supplying the print(transform) from below
    inv_normalize = Normalize(
        mean=[-0.485 / 0.229, -0.456 / 0.224, -0.406 / 0.225],
        std=[1 / 0.229, 1 / 0.224, 1 / 0.225]
    )

    image = inv_normalize(image)
    image = ToPILImage()(image)
    image = CenterCrop(size=(235, 235))(image)
    image = Resize(size=(224, 224), interpolation=2)(image)
    return image